name: Publish Docker image

on:
  release:
    types:
      - published

jobs:
  push_to_registry:
    name: Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: docker/build-push-action@v1
        with:
          repository: ${{ secrets.DOCKER_USERNAME }}/hdcquery
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: latest
          tag_with_ref: true
